#!/bin/sh

# TODO Logs

if [ "$1" == "" ]; then
    echo "Directory must be specified" >&2
    exit 1
elif [ ! -e "$1" ]; then
    echo "Directory not found" >&2
    exit 1
fi

if [ "$2" == "" ]; then
    dirname=$(basename "$1")
else
    dirname="$2"
fi

tar -cJf /tmp/"$dirname".tar.xz -C "$1" .

if [ -e /tmp/"$dirname".tar.xz ]; then

    scp /tmp/"$dirname".tar.xz pi@ssh.martials.no:~/sites-updates

    echo "Folder sent to server"
else
    echo "Failed to create tarball" >&2
    exit 1
fi
